# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 22:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20171105_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='info',
        ),
        migrations.AddField(
            model_name='report',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
