# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20171106_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='company_country',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='company_industry',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='company_location',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='company_name',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='company_phone',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='company_sector',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='current_projects',
            field=models.TextField(default='', help_text='Enter a list of the current projects'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='info',
            field=models.TextField(default='', help_text='Enter information about the business plan and/or project'),
            preserve_default=False,
        ),
    ]
