# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20171106_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
