# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 04:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20171112_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='none', max_length=200)),
                ('password', models.CharField(default='none', max_length=200)),
                ('first_name', models.CharField(default='none', max_length=200)),
                ('last_name', models.CharField(default='none', max_length=200)),
                ('company', models.CharField(default='none', max_length=200)),
                ('email', models.EmailField(default='none', max_length=200)),
                ('user_type', models.CharField(default=1, max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.User'),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
