# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_report_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='isItPrivate',
            field=models.BooleanField(default=True),
        ),
    ]
