# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_message_isitprivate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='group', max_length=50)),
                ('users', models.CharField(default='admin', max_length=50)),
                ('group_reports', models.CharField(default='report', max_length=50)),
            ],
        ),
    ]
