# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20171122_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='filename',
        ),
        migrations.AddField(
            model_name='report',
            name='file',
            field=models.FileField(default=0, max_length=200, upload_to=''),
        ),
    ]
