# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20171126_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='file',
        ),
        migrations.AddField(
            model_name='report',
            name='filename',
            field=models.FileField(default='no file', upload_to='reports/'),
            preserve_default=False,
        ),
    ]
