# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 02:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_auto_20171127_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Report')),
            ],
        ),
    ]
