# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='may_delete_r',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='may_delete_u',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='may_suspend',
            field=models.BooleanField(default=False),
        ),
    ]
