# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_auto_20171127_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_encrypted',
            field=models.BooleanField(default=False),
        ),
    ]
