# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 22:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_auto_20171127_2142'),
        ('catalog', '0020_auto_20171128_1042'),
    ]

    operations = [
    ]
