# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_merge_20171128_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='may_delete_r',
            new_name='has_manager_privileges',
        ),
        migrations.RemoveField(
            model_name='user',
            name='may_delete_u',
        ),
        migrations.RemoveField(
            model_name='user',
            name='may_suspend',
        ),
    ]
