# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_message_symm_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='public_key',
            field=models.TextField(default='publickey'),
            preserve_default=False,
        ),
    ]
