# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='report',
            name='filename',
        ),
        migrations.AddField(
            model_name='file',
            name='report',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
