# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_message_encrypted_msg_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='encrypted_msg_filename',
            field=models.FilePathField(default=' '),
            preserve_default=False,
        ),
    ]
