# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_auto_20171130_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='decrypted_msg_filename',
            field=models.FilePathField(default=' '),
            preserve_default=False,
        ),
    ]
