# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 18:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_auto_20171129_2019'),
        ('catalog', '0029_message_decrypted_msg_file'),
    ]

    operations = [
    ]
