# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_merge_20171130_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_reports',
        ),
        migrations.AddField(
            model_name='group',
            name='group_reports',
            field=models.ManyToManyField(to='catalog.Report'),
        ),
        migrations.AlterField(
            model_name='group',
            name='users',
            field=models.CharField(default='', max_length=200),
        ),
    ]
