# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_auto_20171202_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
