# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0036_report_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='num_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
