# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 02:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0037_report_num_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='decrypted_msg_file',
        ),
        migrations.RemoveField(
            model_name='message',
            name='decrypted_msg_filename',
        ),
    ]
