# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0037_report_num_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(to='catalog.Report'),
        ),
    ]
