# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 04:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0038_user_favorites'),
        ('catalog', '0038_file_encrypted'),
        ('catalog', '0038_auto_20171203_2145'),
    ]

    operations = [
    ]
