# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0039_merge_20171203_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='encrypted_message_body',
            field=models.BinaryField(default=b''),
        ),
    ]
