# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 04:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0040_message_encrypted_message_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='encrypted_msg_filename',
        ),
    ]
