# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 05:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0039_merge_20171203_2305'),
        ('catalog', '0041_remove_message_encrypted_msg_filename'),
    ]

    operations = [
    ]
