# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 22:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0042_merge_20171204_0012'),
        ('catalog', '0039_merge_20171203_2346'),
    ]

    operations = [
    ]
