# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0042_merge_20171204_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='hash_name',
            field=models.CharField(default='made before', max_length=200),
            preserve_default=False,
        ),
    ]
