# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0043_merge_20171204_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='avatar',
            field=models.ImageField(default='media/no-pic.jpg', upload_to=''),
        ),
    ]
