# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0044_report_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='avatar',
            field=models.ImageField(default='pictures/no-pic.jpg', upload_to='pictures/'),
        ),
    ]
