# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 01:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0049_remove_report_avatar'),
        ('catalog', '0043_report_hash_name'),
    ]

    operations = [
    ]
