# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0052_auto_20171205_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='new',
            field=models.BooleanField(default=False),
        ),
    ]
